### ISSUE TITLE
Unclear intention or issue in code await Task.FromResult(base.OnBeforeWriteAsync(args));

### ISSUE THREAD

**Issue by FlorianGrimm** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In the file IntegratedCacheUtils/IntegratedTokenCacheAdapter.cs line 39:  await Task.FromResult(base.OnBeforeWriteAsync(args));
Isn't this odd?
the code awaits the the completed Task from FromResult, but not the inner Task?
```
  protected override async Task OnBeforeWriteAsync(TokenCacheNotificationArgs args)
        {
            var accountActivity = new MsalAccountActivity(args.SuggestedCacheKey, args.Account);
            await UpsertActivity(accountActivity);

            _logger.LogInformation($"{args.SuggestedCacheKey}-{args.Account}");

            await Task.FromResult(base.OnBeforeWriteAsync(args)); //<--- here
        }
```
### Any log messages given by the failure
>

### Expected/desired behavior
> if base.OnBeforeWriteAsync(args) fails the exception is never "catched"

### OS and Version?
> 

### Versions
> Initial commit 99c86430207ca46d42b9af1c21df5444edac7548

### Mention any other details that might be useful

Shouldn't this be
`
await base.OnBeforeWriteAsync(args);
`

or is their any magic that I don't understand? - if so please give me a hint.

Best Regards 
flori

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-michaelmi** [comment]
@FlorianGrimm 

This is a good catch.

It turns out that line isn't needed at all.

The code for the method `MsalDistributedTokenCacheAdapter.OnBeforeWriteAsync` in the [microsoft-identity-web library](https://github.com/AzureAD/microsoft-identity-web) returns a Task that resolves to nothing.

You can see the source code for the **MsalDistributedTokenCacheAdapter**  [here](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs) and the abstract class it inherits from, **MsalAbstractTokenCacheProvider.cs**, [here](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs#L123-L131).

Issue should be resolved with [PR 14](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/pull/14)
